# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 14e19ca68a403e64e4d52de0f53b9efed8811535fa81e703efcd30211336e76b36fed80d68675b01d5496755f3c9e79fb2d4a05ab51894714dad5dc078c92672

test:
  secret_key_base: fac5b9e2bfbcd65991a1ca244b08381d0323a276e17a82b8b8d9911b24198e22e020cce76b065b205a48051629d6b67acd2754c08195dedf7dfbda076507fbce

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
